import LocalizedStrings from "react-localization";

export const Localizations = new LocalizedStrings({
  es: {
    underConstruction: "(Sitio en construcción)",
    simplifyingHealth: "Simplificando tu camino a la salud.",
    learnMoreProject: "Conoce Nuestro Proyecto",
    preventiveMedicine: "LA MEDICINA PREVENTIVA ES LA CLAVE",
    supdocDescription:
      "SupDoc es una aplicación de salud diseñada para reducir la sobrecarga en las consultas con especialistas y los servicios de atención médica. Proporciona una plataforma simple, confiable y segura, que permite a los usuarios recibir atención médica virtual de manera anónima.",
    contactEmail: "Correo electrónico",
    privacyPolicy: "Política de Privacidad",
    links: "Enlaces",
    home: "Inicio",
    mission: "Misión",
    advances: "Nuestros Avances",
    meetTeam: "Conoce al Equipo",
    resources: "Recursos",
    team: "Equipo",
    roles: {
      programmer: "Programador",
      videoDirector: "Director de Video",
      graphicDesigner: "Diseñador Gráfico",
    },
  },
  en: {
    underConstruction: "(Site under construction)",
    simplifyingHealth: "Simplifying your path to health.",
    learnMoreProject: "Learn More",
    preventiveMedicine: "PREVENTIVE MEDICINE IS KEY",
    supdocDescription:
      "SupDoc is a health app designed to reduce the overload in specialist consultations and healthcare services. It provides a simple, reliable, and secure platform, allowing users to receive virtual medical care anonymously.",
    contactEmail: "Email",
    privacyPolicy: "Privacy Policy",
    links: "Links",
    home: "Home",
    mission: "Mission",
    advances: "Our Advances",
    meetTeam: "Meet the Team",
    resources: "Resources",
    team: "Team",
    roles: {
      programmer: "Programmer",
      videoDirector: "Video Director",
      graphicDesigner: "Graphic Designer",
    },
  },
  zh: {
    underConstruction: "（网站建设中）",
    simplifyingHealth: "简化您的健康之路。",
    learnMoreProject: "了解更多",
    preventiveMedicine: "预防医学是关键",
    supdocDescription:
      "SupDoc 是一款健康应用，旨在减少专家咨询和医疗服务的过载。它提供了一个简单、可靠和安全的平台，使用户能够匿名接收虚拟医疗服务。",
    contactEmail: "电子邮件",
    privacyPolicy: "隐私政策",
    links: "链接",
    home: "首页",
    mission: "使命",
    advances: "我们的进展",
    meetTeam: "认识团队",
    resources: "资源",
    team: "团队",
    roles: {
      programmer: "程序员",
      videoDirector: "视频导演",
      graphicDesigner: "平面设计师",
    },
  },
  hi: {
    underConstruction: "(साइट निर्माणाधीन है)",
    simplifyingHealth: "आपके स्वास्थ्य का रास्ता सरल बना रहे हैं।",
    learnMoreProject: "और जानें",
    preventiveMedicine: "रोकथाम चिकित्सा महत्वपूर्ण है",
    supdocDescription:
      "SupDoc एक स्वास्थ्य ऐप है जिसे विशेषज्ञ परामर्श और स्वास्थ्य सेवाओं के अधिभार को कम करने के लिए डिज़ाइन किया गया है। यह एक सरल, विश्वसनीय और सुरक्षित प्लेटफ़ॉर्म प्रदान करता है, जो उपयोगकर्ताओं को गुमनाम रूप से आभासी चिकित्सा देखभाल प्राप्त करने की अनुमति देता है।",
    contactEmail: "ईमेल",
    privacyPolicy: "गोपनीयता नीति",
    links: "लिंक",
    home: "होम",
    mission: "मिशन",
    advances: "हमारी प्रगति",
    meetTeam: "टीम से मिलें",
    resources: "संसाधन",
    team: "टीम",
    roles: {
      programmer: "प्रोग्रामर",
      videoDirector: "वीडियो निर्देशक",
      graphicDesigner: "ग्राफिक डिज़ाइनर",
    },
  },
  pt: {
    underConstruction: "(Site em construção)",
    simplifyingHealth: "Simplificando o seu caminho para a saúde.",
    learnMoreProject: "Saiba Mais",
    preventiveMedicine: "A MEDICINA PREVENTIVA É FUNDAMENTAL",
    supdocDescription:
      "O SupDoc é um aplicativo de saúde projetado para reduzir a sobrecarga nas consultas com especialistas e nos serviços de saúde. Ele oferece uma plataforma simples, confiável e segura, permitindo que os usuários recebam atendimento médico virtual de forma anônima.",
    contactEmail: "E-mail",
    privacyPolicy: "Política de Privacidade",
    links: "Links",
    home: "Início",
    mission: "Missão",
    advances: "Nossos Avanços",
    meetTeam: "Conheça a Equipe",
    resources: "Recursos",
    team: "Equipe",
    roles: {
      programmer: "Programador",
      videoDirector: "Diretor de Vídeo",
      graphicDesigner: "Designer Gráfico",
    },
  },
  ar: {
    underConstruction: "(الموقع قيد الإنشاء)",
    simplifyingHealth: "تبسيط طريقك إلى الصحة.",
    learnMoreProject: "اعرف المزيد",
    preventiveMedicine: "الطب الوقائي هو المفتاح",
    supdocDescription:
      "SupDoc هو تطبيق صحي مصمم لتقليل الضغط على الاستشارات المتخصصة وخدمات الرعاية الصحية. يوفر منصة بسيطة وموثوقة وآمنة، مما يسمح للمستخدمين بتلقي الرعاية الطبية الافتراضية بشكل مجهول.",
    contactEmail: "البريد الإلكتروني",
    privacyPolicy: "سياسة الخصوصية",
    links: "الروابط",
    home: "الرئيسية",
    mission: "المهمة",
    advances: "تقدمنا",
    meetTeam: "تعرف على الفريق",
    resources: "الموارد",
    team: "الفريق",
    roles: {
      programmer: "مبرمج",
      videoDirector: "مخرج فيديو",
      graphicDesigner: "مصمم جرافيك",
    },
  },
  fr: {
    underConstruction: "(Site en construction)",
    simplifyingHealth: "Simplifier votre chemin vers la santé.",
    learnMoreProject: "En savoir plus",
    preventiveMedicine: "LA MÉDECINE PRÉVENTIVE EST LA CLÉ",
    supdocDescription:
      "SupDoc est une application de santé conçue pour réduire la surcharge des consultations spécialisées et des services de santé. Elle fournit une plateforme simple, fiable et sécurisée, permettant aux utilisateurs de recevoir des soins médicaux virtuels de manière anonyme.",
    contactEmail: "Email",
    privacyPolicy: "Politique de confidentialité",
    links: "Liens",
    home: "Accueil",
    mission: "Mission",
    advances: "Nos Avancées",
    meetTeam: "Rencontrez l'équipe",
    resources: "Ressources",
    team: "Équipe",
    roles: {
      programmer: "Programmeur",
      videoDirector: "Réalisateur vidéo",
      graphicDesigner: "Graphiste",
    },
  },
  de: {
    underConstruction: "(Seite im Aufbau)",
    simplifyingHealth: "Vereinfachen Sie Ihren Weg zur Gesundheit.",
    learnMoreProject: "Erfahren Sie mehr",
    preventiveMedicine: "PRÄVENTIVMEDIZIN IST DER SCHLÜSSEL",
    supdocDescription:
      "SupDoc ist eine Gesundheits-App, die entwickelt wurde, um die Überlastung bei Facharztkonsultationen und Gesundheitsdiensten zu verringern. Sie bietet eine einfache, zuverlässige und sichere Plattform, die es den Nutzern ermöglicht, anonym virtuelle medizinische Versorgung zu erhalten.",
    contactEmail: "E-Mail",
    privacyPolicy: "Datenschutzrichtlinie",
    links: "Links",
    home: "Startseite",
    mission: "Mission",
    advances: "Unsere Fortschritte",
    meetTeam: "Das Team kennenlernen",
    resources: "Ressourcen",
    team: "Team",
    roles: {
      programmer: "Programmierer",
      videoDirector: "Video-Regisseur",
      graphicDesigner: "Grafikdesigner",
    },
  },
  ru: {
    underConstruction: "(Сайт в разработке)",
    simplifyingHealth: "Упрощаем ваш путь к здоровью.",
    learnMoreProject: "Узнать больше",
    preventiveMedicine: "ПРЕДУПРЕДИТЕЛЬНАЯ МЕДИЦИНА - ЭТО КЛЮЧ",
    supdocDescription:
      "SupDoc - это приложение для здоровья, разработанное для снижения нагрузки на консультации специалистов и медицинские услуги. Оно предоставляет простую, надежную и безопасную платформу, позволяющую пользователям получать виртуальную медицинскую помощь анонимно.",
    contactEmail: "Электронная почта",
    privacyPolicy: "Политика конфиденциальности",
    links: "Ссылки",
    home: "Главная",
    mission: "Миссия",
    advances: "Наши достижения",
    meetTeam: "Встретьтесь с командой",
    resources: "Ресурсы",
    team: "Команда",
    roles: {
      programmer: "Программист",
      videoDirector: "Режиссер видео",
      graphicDesigner: "Графический дизайнер",
    },
  },
  ja: {
    underConstruction: "（サイトは工事中です）",
    simplifyingHealth: "健康への道を簡素化します。",
    learnMoreProject: "もっと詳しく知る",
    preventiveMedicine: "予防医学は鍵です",
    supdocDescription:
      "SupDocは、専門医の相談や医療サービスの過負荷を軽減するために設計された健康アプリです。シンプルで信頼性が高く安全なプラットフォームを提供し、ユーザーが匿名でバーチャル医療を受けることができるようにします。",
    contactEmail: "メール",
    privacyPolicy: "プライバシーポリシー",
    links: "リンク",
    home: "ホーム",
    mission: "ミッション",
    advances: "私たちの進歩",
    meetTeam: "チームに会う",
    resources: "リソース",
    team: "チーム",
    roles: {
      programmer: "プログラマー",
      videoDirector: "ビデオディレクター",
      graphicDesigner: "グラフィックデザイナー",
    },
  },
  ko: {
    underConstruction: "(사이트 공사 중)",
    simplifyingHealth: "건강으로 가는 길을 단순화합니다.",
    learnMoreProject: "더 알아보기",
    preventiveMedicine: "예방 의학이 중요합니다",
    supdocDescription:
      "SupDoc는 전문 상담 및 의료 서비스의 과부하를 줄이기 위해 설계된 건강 앱입니다. 사용자가 익명으로 가상 의료 서비스를 받을 수 있는 간단하고 신뢰할 수 있으며 안전한 플랫폼을 제공합니다.",
    contactEmail: "이메일",
    privacyPolicy: "개인정보 보호정책",
    links: "링크",
    home: "홈",
    mission: "미션",
    advances: "우리의 진전",
    meetTeam: "팀 만나기",
    resources: "자원",
    team: "팀",
    roles: {
      programmer: "프로그래머",
      videoDirector: "비디오 감독",
      graphicDesigner: "그래픽 디자이너",
    },
  },
  it: {
    underConstruction: "(Sito in costruzione)",
    simplifyingHealth: "Semplificando il tuo percorso verso la salute.",
    learnMoreProject: "Scopri di più",
    preventiveMedicine: "LA MEDICINA PREVENTIVA È LA CHIAVE",
    supdocDescription:
      "SupDoc è un'app per la salute progettata per ridurre il sovraccarico nelle consultazioni specialistiche e nei servizi sanitari. Fornisce una piattaforma semplice, affidabile e sicura, consentendo agli utenti di ricevere assistenza medica virtuale in modo anonimo.",
    contactEmail: "Email",
    privacyPolicy: "Informativa sulla privacy",
    links: "Link",
    home: "Home",
    mission: "Missione",
    advances: "I nostri progressi",
    meetTeam: "Incontra il team",
    resources: "Risorse",
    team: "Team",
    roles: {
      programmer: "Programmatore",
      videoDirector: "Regista video",
      graphicDesigner: "Grafico",
    },
  },
});
