enum STATUS_CODES {
  SUCCESS,
  GENERIC_ERROR,
  USER_NOT_FOUND,
  TOO_MANY_ATTEMPTS,
  INVALID_NUMBER,
  SENT_CODE,
  NUMBER_NOT_EXIST,
  ERROR_SENDING_CODE,
  CODE_DENIED,
  CODE_EXPIRED,
  CODE_FAILED,
  NO_CONNECTION,
  ID_IN_USE,
  NUMBER_IN_USE,
  NONE_IN_USE,
}
export default STATUS_CODES;
